model_list:
  model_name: ollama-llama2
    litellm_params:
      model: "ollama/llama2"
      api_base: "http://127.0.0.1:8003"
      headers: {
        "HTTP-Referer": "litellm.ai",  
        "X-Title": "LiteLLM Server"
      }
